// src/components/dw-survey-comp/dw-answer-comp/dw-answer-survey-question/dw-answer-questions/dw-answer-qu-checkbox/DwAnswerQuCheckbox.tsx
import React from 'react';
import DwQuCheckboxOptions from './components/DwQuCheckboxOptions';

interface DwAnswerQuCheckboxProps {
  index: number;
  survey: any;
  answer: any;
  onSurveyChange: (survey: any) => void;
}

const DwAnswerQuCheckbox: React.FC<DwAnswerQuCheckboxProps> = ({ index = 0, survey = {}, answer = {}, onSurveyChange }) => {

  return (
    <DwQuCheckboxOptions
      survey={survey}
      onSurveyChange={onSurveyChange}
      index={index}
      answer={answer}
    />
  );
};

export default DwAnswerQuCheckbox;

// src/components/dw-survey-comp/dw-answer-comp/dw-answer-survey-question/dw-answer-questions/dw-answer-qu-checkbox/DwAnswerQuCheckbox.vue
<template>
  <dw-qu-checkbox-options ref="dwQuestion" v-model="survey" :index="index"></dw-qu-checkbox-options>
</template>

<script>
import DwQuCheckboxOptions from './components/DwQuCheckboxOptions'
export default {
  name: 'DwAnswerQuCheckbox',
  components: {DwQuCheckboxOptions},
  model: {
    prop: 'survey',
    event: 'update-survey'
  },
  props: {
    index: {type: Number, default: 0},
    survey: {type: Object, default: () => {}},
    answer: {type: Object, default: () => {}}
  }
}
</script>
