// src/components/dw-survey-comp/dw-answer-comp/dw-answer-survey-question/dw-answer-questions/dw-answer-qu-matrix/common/dw-answer-matrix-common1/DwAnswerQuMatrixOptionCommon1.tsx
import React from 'react';
import { Input, message } from 'antd';
import DwHtmlLabelCommon from '../../../../../dw-answer-survey-common/DwHtmlLabelCommon';
import { answerQuEventCommon } from '../../../../../dw-utils/dw-survey-answer-common';
import { showReadNotify } from '../../../../../../dw-utils/dw-common/dw-msg-common';
import './DwAnswerQuMatrixOptionCommon1.css';

interface DwAnswerQuMatrixOptionCommon1Props {
  index: number;
  survey: any;
  quType: string;
  onSurveyChange: (survey: any) => void;
}

const DwAnswerQuMatrixOptionCommon1: React.FC<DwAnswerQuMatrixOptionCommon1Props> = ({ index = 0, survey = {}, quType = '', onSurveyChange }) => {
  const resetOtherRadio = (rowIndex: number, colIndex: number) => {
    const newSurvey = { ...survey };
    newSurvey.questions[index].quRows[rowIndex].rowCols.forEach((item: any, idx: number) => {
      item.checked = idx === colIndex;
    });
    onSurveyChange(newSurvey);
  };

  const clickItem = (rowIndex: number, colIndex: number) => {
    if (survey.readonly) return showReadNotify('readonly');

    const newSurvey = { ...survey };
    const rowCols = newSurvey.questions[index].quRows[rowIndex].rowCols;

    if (quType === 'MATRIX_RADIO') {
      resetOtherRadio(rowIndex, colIndex);
    } else if (quType === 'MATRIX_CHECKBOX') {
      rowCols[colIndex].checked = !rowCols[colIndex].checked;
      onSurveyChange(newSurvey);
    }

    onBlur();
  };

  const handleInputChange = (rowIndex: number, colIndex: number, value: string) => {
    const newSurvey = { ...survey };
    newSurvey.questions[index].quRows[rowIndex].rowCols[colIndex].answerValue = value;
    onSurveyChange(newSurvey);
  };

  const onBlur = () => {
    answerQuEventCommon(survey, index);
  };

  if (!survey.questions?.[index]?.quCols || survey.questions[index].quCols.length === 0) {
    return null;
  }

  return (
    <div style={{ padding: 0 }}>
      <div>
        <div style={{ overflowX: 'scroll', width: '100%', display: 'block' }}>
          <table>
            <thead>
              <tr>
                <td 
                  colSpan={survey.questions[index].quCols.length - 1} 
                  className="dw-matrix-row-title-td" 
                  style={{ padding: '0 0 5px 0' }}
                >
                  <div className="dw-display-flex">
                    <div style={{ 
                      position: 'sticky', 
                      left: 0, 
                      zIndex: 1, 
                      paddingLeft: '5px', 
                      fontSize: '12px', 
                      color: '#afafb0'
                    }}>
                      如显示不全，试试在矩阵表区域左右滑动
                    </div>
                    <div style={{ flexGrow: 1 }}></div>
                  </div>
                </td>
              </tr>
              <tr className="dw-el-radio-checkbox-tr">
                {survey.questions[index].quCols.map((colOption: any) => (
                  !colOption.tempEmptyOption && (
                    <td key={`col_${colOption.dwId}`} className="matrix-title-td">
                      <DwHtmlLabelCommon value={colOption.optionTitleObj} />
                    </td>
                  )
                ))}
              </tr>
            </thead>
            <tbody>
              {survey.questions[index].quRows.map((rowOption: any, rowOptionIndex: number) => (
                <React.Fragment key={`matrix-rowOption-${rowOption.dwId}`}>
                  <tr>
                    <td 
                      colSpan={survey.questions[index].quCols.length - 1} 
                      className="dw-matrix-row-title-td" 
                      style={{ textAlign: 'left' }}
                    >
                      <div className="dw-display-flex">
                        <div style={{ position: 'sticky', left: 0, zIndex: 1, paddingLeft: '5px' }}>
                          <DwHtmlLabelCommon value={rowOption.optionTitleObj} />
                        </div>
                        <div style={{ flexGrow: 1 }}></div>
                      </div>
                    </td>
                  </tr>
                  <tr className="dw-el-radio-checkbox-tr">
                    {survey.questions[index].quCols.map((colOption: any, colIndex: number) => (
                      !colOption.tempEmptyOption && (
                        <td 
                          key={`matrix-colOption-content-${colIndex}`} 
                          onClick={() => clickItem(rowOptionIndex, colIndex)}
                        >
                          {quType === 'MATRIX_RADIO' && (
                            <div className="dw-qu-item-el-checkbox-radio dw-item-checked matrix-item">
                              {rowOption.rowCols[colIndex].checked ? (
                                <i className="dw-qu-item-el-checkbox-radio-icon dw-radio-icon fa-solid fa-circle-dot animate__animated animate__tada dw-checked" />
                              ) : (
                                <i className="dw-qu-item-el-checkbox-radio-icon dw-radio-icon fa-regular fa-circle" />
                              )}
                            </div>
                          )}
                          {quType === 'MATRIX_CHECKBOX' && (
                            <div className="dw-qu-item-el-checkbox-radio dw-item-checked matrix-item">
                              {rowOption.rowCols[colIndex].checked ? (
                                <i className="dw-qu-item-el-checkbox-radio-icon dw-checkbox-icon fa-solid fa-square-check animate__animated animate__tada dw-checked" />
                              ) : (
                                <i className="dw-qu-item-el-checkbox-radio-icon dw-checkbox-icon fa-regular fa-square" />
                              )}
                            </div>
                          )}
                          {quType === 'MATRIX_INPUT' && (
                            <div style={{ padding: '5px' }}>
                              <Input
                                value={rowOption.rowCols[colIndex].answerValue}
                                placeholder="请输入"
                                onChange={(e) => handleInputChange(rowOptionIndex, colIndex, e.target.value)}
                                onBlur={onBlur}
                              />
                            </div>
                          )}
                        </td>
                      )
                    ))}
                  </tr>
                </React.Fragment>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default DwAnswerQuMatrixOptionCommon1;

// src/components/dw-survey-comp/dw-answer-comp/dw-answer-survey-question/dw-answer-questions/dw-answer-qu-matrix/common/dw-answer-matrix-common1/DwAnswerQuMatrixOptionCommon1.vue
<template>
  <div style="padding: 0;">
    <div>
      <div v-if="survey.questions[index].hasOwnProperty('quCols') && survey.questions[index].quCols!==null && survey.questions[index].quCols.length>0" style="overflow-x: scroll;width: 100%;display: block;">
        <table>
          <thead>
            <tr>
              <td :colspan="survey.questions[index].quCols.length-1" class="dw-matrix-row-title-td" style="padding: 0 0 5px 0;">
                <div class="dw-display-flex">
                  <div style="position: sticky;left: 0;z-index: 1;padding-left: 5px;font-size: 12px;color: #afafb0;">如显示不全，试试在矩阵表区域左右滑动</div>
                  <div style="flex-grow: 1;"></div>
                </div>
              </td>
            </tr>
            <tr class="dw-el-radio-checkbox-tr">
              <template v-for="(colOption) in survey.questions[index].quCols">
                <td v-if="!colOption.tempEmptyOption" :key="`col_${colOption.dwId}`" class="matrix-title-td">
                  <dw-html-label-common ref="dwEditLabel" :value="colOption.optionTitleObj"></dw-html-label-common>
                </td>
              </template>
            </tr>
          </thead>
          <tbody v-for="(rowOption, rowOptionIndex) in survey.questions[index].quRows" :key="`matrix-rowOption-${rowOption.dwId}`">
            <tr>
              <td :colspan="survey.questions[index].quCols.length-1" class="dw-matrix-row-title-td" style="text-align: left;">
                <div class="dw-display-flex">
                  <div style="position: sticky;left: 0;z-index: 1;padding-left: 5px;">
                    <dw-html-label-common ref="dwEditLabel" :value="rowOption.optionTitleObj"></dw-html-label-common>
                  </div>
                  <div style="flex-grow: 1;"></div>
                </div>
              </td>
            </tr>
            <tr class="dw-el-radio-checkbox-tr">
              <template v-for="(colOption, colIndex) in survey.questions[index].quCols">
                <td v-if="!colOption.tempEmptyOption" :key="`matrix-colOption-content-${colIndex}`" @click.stop="clickItem(rowOptionIndex,colIndex)">
                  <template v-if="quType === 'MATRIX_RADIO'">
                    <div class="dw-qu-item-el-checkbox-radio dw-item-checked matrix-item">
                      <i v-if="survey.questions[index].quRows[rowOptionIndex].rowCols[colIndex].checked" class="dw-qu-item-el-checkbox-radio-icon dw-radio-icon fa-solid fa-circle-dot animate__animated animate__tada dw-checked"></i>
                      <i v-else class="dw-qu-item-el-checkbox-radio-icon dw-radio-icon fa-regular fa-circle"></i>
                    </div>
                  </template>
                  <template v-else-if="quType === 'MATRIX_CHECKBOX'">
                    <div class="dw-qu-item-el-checkbox-radio dw-item-checked matrix-item">
                      <i v-if="survey.questions[index].quRows[rowOptionIndex].rowCols[colIndex].checked" class="dw-qu-item-el-checkbox-radio-icon dw-checkbox-icon fa-solid fa-square-check animate__animated animate__tada dw-checked"></i>
                      <i v-else class="dw-qu-item-el-checkbox-radio-icon dw-checkbox-icon fa-regular fa-square"></i>
                    </div>
                  </template>
                  <template v-else-if="quType === 'MATRIX_INPUT'">
                    <div style="padding: 5px;">
                      <el-input v-model="survey.questions[index].quRows[rowOptionIndex].rowCols[colIndex].answerValue" placeholder="请输入" @blur="onBlur"></el-input>
                    </div>
                  </template>
                </td>
              </template>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script>

import DwHtmlLabelCommon from '../../../../../dw-answer-survey-common/DwHtmlLabelCommon.vue'
import {showReadNotify} from '../../../../../../dw-utils/dw-common/dw-msg-common'
import {answerQuEventCommon} from '../../../../../dw-utils/dw-survey-answer-common'

export default {
  name: 'DwAnswerQuMatrixOptionCommon1',
  components: {DwHtmlLabelCommon},
  model: {
    prop: 'survey',
    event: 'update-survey'
  },
  props: {
    index: {type: Number, default: 0},
    survey: {type: Object, default: () => {}},
    quType: {type: String, default: ''}
  },
  data () {
    return {
    }
  },
  methods: {
    resetOtherRadio (rowIndex) {
      const quRadios = this.survey.questions[this.index].quRows[rowIndex].rowCols
      quRadios.forEach((item, index) => { if (index !== this.optionIndex) item.checked = false })
    },
    clickItem (rowIndex, colIndex) {
      if (this.survey.readonly) return showReadNotify(this)
      // 如果是多选题
      const quType = this.quType
      console.debug('clickItem quType', quType)
      if (quType === 'MATRIX_RADIO') {
        // this.survey.questions[this.quIndex].quRadios[this.optionIndex].checked = true
        this.resetOtherRadio(rowIndex)
        this.survey.questions[this.index].quRows[rowIndex].rowCols[colIndex].checked = true
      } else if (quType === 'MATRIX_CHECKBOX') {
        this.survey.questions[this.index].quRows[rowIndex].rowCols[colIndex].checked = !this.survey.questions[this.index].quRows[rowIndex].rowCols[colIndex].checked
      } else if (quType === 'SCORE') {
        this.survey.questions[this.index].quScores[this.optionIndex].checked = true
      }
      // 题目检查
      this.onBlur()
    },
    onBlur () {
      // 同步答案
      answerQuEventCommon(this.survey, this.index)
    }
  }
}
</script>

<style scoped>
table,tbody,tr,th,td{
  border-spacing: 0;
  border: none;
}
table{
  text-align: center;
  border-spacing: 0;
  width: 100%;
  min-width: 100%;
  max-width: none;
  border-radius: 3px;
}
/* 交替行颜色 */
thead tr:nth-child(odd) {
  background-color: white;
}
/* 偶数行颜色 */
thead tr:nth-child(even) {
  background-color: #d8d8d9;
}
.matrix-title-td{
  padding: 10px 5px;
  white-space: nowrap;
}
.dw-matrix-row-title-td{
  padding: 10px 0;
}
/* 交替行颜色 */
tbody tr:nth-child(odd) {
  background-color: #f9f9f9;
}
/* 偶数行颜色 */
tbody tr:nth-child(even) {
  background-color: #f0f0f0;
}
/*tr.dw-el-radio-checkbox-tr td:nth-child(1)
 {
   background-color: rgb(114, 224, 129);
 }*/
tbody tr:last-child td{
  border-bottom: 1px solid #e7e7e8;
}
</style>
