// src/components/dw-survey-comp/dw-answer-comp/dw-answer-survey-question/dw-answer-questions/dw-answer-qu-matrix/dw-answer-qu-matrix-scale/DwAnswerQuMatrixScale.tsx
import React from 'react';
import DwAnswerQuMatrixOptionCommon2 from '../common/dw-answer-matrix-common2/DwAnswerQuMatrixOptionCommon2.tsx';

interface Question {
  quType: string;
  // Add other question properties as needed
}

interface Survey {
  questions: Question[];
  // Add other survey properties as needed
}

interface Answer {
  // Define answer properties as needed
}

interface DwAnswerQuMatrixScaleProps {
  index?: number;
  survey: Survey;
  answer?: Answer;
  onUpdateSurvey?: (updatedSurvey: Survey) => void;
}

const DwAnswerQuMatrixScale: React.FC<DwAnswerQuMatrixScaleProps> = ({
  index = 0,
  survey,
  answer,
  onUpdateSurvey
}) => {
  const handleSurveyUpdate = (updatedSurvey: Survey) => {
    if (onUpdateSurvey) {
      onUpdateSurvey(updatedSurvey);
    }
  };

  return (
    <DwAnswerQuMatrixOptionCommon2
      index={index}
      survey={survey}
      quType={survey.questions[index].quType}
      onSurveyChange={handleSurveyUpdate}
    />
  );
};

export default DwAnswerQuMatrixScale;

// src/components/dw-survey-comp/dw-answer-comp/dw-answer-survey-question/dw-answer-questions/dw-answer-qu-matrix/dw-answer-qu-matrix-scale/DwAnswerQuMatrixScale.vue
<template>
  <dw-answer-qu-matrix-option-common2 v-model="survey" :index="index" :qu-type="survey.questions[index].quType"></dw-answer-qu-matrix-option-common2>
</template>

<script>
import DwAnswerQuMatrixOptionCommon2 from '../common/dw-answer-matrix-common2/DwAnswerQuMatrixOptionCommon2.vue'

export default {
  name: 'DwAnswerQuMatrixScale',
  components: {DwAnswerQuMatrixOptionCommon2},
  model: {
    prop: 'survey',
    event: 'update-survey'
  },
  props: {
    index: {type: Number, default: 0},
    survey: {type: Object, default: () => {}},
    answer: {type: Object, default: () => {}}
  }
}
</script>
