// src/components/dw-survey-comp/dw-answer-comp/dw-answer-survey-question/dw-answer-questions/dw-answer-qu-orderby/components/DwQuOrderOptions.vue
<template>
  <div class="dw-qu-order-group">
    <!--   v-for的key不能是index，如下用item，不然动画会没有效果 -->
    <transition-group name="flip-list">
      <div v-for="(item, optionIndex) in survey.questions[index].quOrderbys" :key="survey.tempDataType === 'modelComponents' ? `orderBy-${optionIndex}`: item.dwId" class="dw-qu-order-group-item dwMoveSortQuOption">
        <div class="dw-qu-item" @click="clickItem(item)">
          <div class="dw-qu-item-body">
            <div :class="item.checked ? `dw-item-checked`: ''" class="dw-qu-item-body-order-option">
              <i v-if="item.orderIndex>0" :style="`background: ${themeColor};border-color: ${themeColor}`" class="fa dw-qu-order-num dw-num-order animate__animated animate__tada">{{ item.orderIndex }}</i>
              <i v-else class="fa dw-qu-order-num dw-num-empty"> {{ item.orderIndex }} </i>
              <div class="dw-qu-item-option-title"><dw-html-label-common ref="dwEditLabel" :value="item.optionTitleObj"></dw-html-label-common></div>
            </div>
          </div>
        </div>
      </div>
    </transition-group>
  </div>
</template>

<script>

import DwHtmlLabelCommon from '../../../../dw-answer-survey-common/DwHtmlLabelCommon.vue'
import {showReadNotify} from '../../../../../dw-utils/dw-common/dw-msg-common'
import {answerQuEventCommon} from '../../../../dw-utils/dw-survey-answer-common'

export default {
  name: 'DwQuOrderOptions',
  components: {DwHtmlLabelCommon},
  model: {
    prop: 'survey',
    event: 'update-survey'
  },
  props: {
    index: {type: Number, default: 0},
    survey: {type: Object, default: () => {}}
  },
  data () {
    return {
      dataNum: 0,
      themeColor: this.survey.surveyStyle.themeColor
    }
  },
  mounted () {
    this.survey.questions[this.index].quOrderbys.forEach((option, index) => {
      if (this.dataNum < option.orderIndex) this.dataNum = option.orderIndex
    })
  },
  methods: {
    onStart () {
      this.drag = true
    },
    onEnd (attrs) {
      this.drag = false
    },
    clickItem (item) {
      if (!this.survey.questions[this.index].hasOwnProperty('anQuestion')) this.dataNum = 0
      if (this.survey.readonly) return showReadNotify(this)
      item.checked = !item.checked
      const length = this.survey.questions[this.index].quOrderbys.length
      if (item.hasOwnProperty('orderIndex') && item.orderIndex > 0) {
        const itemOrderIndex = item.orderIndex
        this.survey.questions[this.index].quOrderbys.forEach((option, index) => {
          if (itemOrderIndex < option.orderIndex) {
            option.orderIndex = option.orderIndex - 1
          }
        })
        item.orderIndex = 0
        const newNum = this.dataNum - 1
        if (newNum >= 0) this.dataNum = newNum
      } else {
        const newNum = this.dataNum + 1
        if (newNum <= length) {
          item.orderIndex = newNum
          this.dataNum = newNum
        }
      }
      this.survey.questions[this.index].quOrderbys.sort(function (a, b) {
        const x = a.orderIndex === 0 ? length + 1 : a.orderIndex
        const y = b.orderIndex === 0 ? length + 1 : b.orderIndex
        return ((x < y) ? -1 : (x > y) ? 1 : 0)
      })
      // getQuestionAnswerData(this.survey.questions[this.index])
      // validateQuestion(this.survey.questions[this.index])
      answerQuEventCommon(this.survey, this.index)
    }
  }
}
</script>

<style scoped>
@import '../../../../../../../assets/css/dw-answer.css';
.dw-qu-order-group{
  margin-bottom: 5px;
}
.dw-qu-order-group .dw-qu-order-group-item{
  border: 1px solid #efefef;
  background: white;
  /*margin-bottom: -1px;*/
  margin-bottom: 5px;
  border-radius: 2px;
}
.dw-qu-item-body-order-option{
  /*display: inline-flex;*/
  display: flex;
  align-items: center;
  font-size: 14px;
  padding: 3px 5px;
}
.dw-qu-order-num{
  border: 1px solid #ccc;
  font-size: 10px;
  padding: 3px 5px;
  margin-right: 5px;
  font-family: "Antic", "Tahoma", serif;
  border-radius: 3px;
}
.dw-qu-order-num.dw-num-empty{
  color: white;
  background: white;
}
.flip-list-move {
  transition: transform 0.5s;
}

</style>

// src/components/dw-survey-comp/dw-answer-comp/dw-answer-survey-question/dw-answer-questions/dw-answer-qu-orderby/components/DwQuOrderOptions.tsx
import React, { useState, useEffect } from 'react';
import { Form, Tag, Card } from 'antd';
import { TransitionGroup, CSSTransition } from 'react-transition-group';
import DwHtmlLabelCommon from '../../../../dw-answer-survey-common/DwHtmlLabelCommon.tsx';
import { showReadNotify } from '../../../../../dw-utils/dw-common/dw-msg-common';
import { answerQuEventCommon } from '../../../../dw-utils/dw-survey-answer-common';
import '../../../../../../../assets/css/dw-answer.css';
import './DwQuOrderOptions.css'; // Import the converted CSS

interface QuOrderby {
  dwId?: string;
  checked: boolean;
  orderIndex: number;
  optionTitleObj: any;
  [key: string]: any;
}

interface Question {
  quOrderbys: QuOrderby[];
  [key: string]: any;
}

interface Survey {
  questions: Question[];
  surveyStyle: {
    themeColor: string;
  };
  readonly?: boolean;
  tempDataType?: string;
  [key: string]: any;
}

interface DwQuOrderOptionsProps {
  index?: number;
  survey: Survey;
  onUpdateOptions?: (options: any[]) => void;
}

const DwQuOrderOptions: React.FC<DwQuOrderOptionsProps> = ({
  index = 0,
  survey,
  onUpdateOptions
}) => {
  const [dataNum, setDataNum] = useState(0);
  const [drag, setDrag] = useState(false);
  const themeColor = survey.surveyStyle.themeColor;

  useEffect(() => {
    let maxNum = 0;
    survey.questions[index].quOrderbys.forEach((option) => {
      if (maxNum < option.orderIndex) maxNum = option.orderIndex;
    });
    setDataNum(maxNum);
  }, [index, survey]);

  const clickItem = (item: QuOrderby) => {
    if (!survey.questions[index].hasOwnProperty('anQuestion')) setDataNum(0);
    if (survey.readonly) return showReadNotify(survey);

    const updatedSurvey = { ...survey };
    const quOrderbys = [...updatedSurvey.questions[index].quOrderbys];
    const itemIndex = quOrderbys.findIndex(opt => opt.dwId === item.dwId);
    
    if (itemIndex === -1) return;

    quOrderbys[itemIndex].checked = !quOrderbys[itemIndex].checked;
    const length = quOrderbys.length;

    if (quOrderbys[itemIndex].orderIndex > 0) {
      const itemOrderIndex = quOrderbys[itemIndex].orderIndex;
      quOrderbys.forEach((option) => {
        if (itemOrderIndex < option.orderIndex) {
          option.orderIndex -= 1;
        }
      });
      quOrderbys[itemIndex].orderIndex = 0;
      const newNum = dataNum - 1;
      if (newNum >= 0) setDataNum(newNum);
    } else {
      const newNum = dataNum + 1;
      if (newNum <= length) {
        quOrderbys[itemIndex].orderIndex = newNum;
        setDataNum(newNum);
      }
    }

    quOrderbys.sort((a, b) => {
      const x = a.orderIndex === 0 ? length + 1 : a.orderIndex;
      const y = b.orderIndex === 0 ? length + 1 : b.orderIndex;
      return x < y ? -1 : x > y ? 1 : 0;
    });

    updatedSurvey.questions[index].quOrderbys = quOrderbys;
    if (onUpdateOptions) onUpdateOptions(updatedSurvey.questions[index].quOrderbys);
    answerQuEventCommon(updatedSurvey, index);
  };

  return (
    <Form>
      <div className="dw-qu-order-group">
        <TransitionGroup component={null}>
          {survey.questions[index].quOrderbys.map((item, optionIndex) => {
            const key = survey.tempDataType === 'modelComponents' 
              ? `orderBy-${optionIndex}` 
              : item.dwId || optionIndex;

            return (
              <CSSTransition
                key={key}
                timeout={500}
                classNames="flip-list"
              >
                <Card
                  className="dw-qu-order-group-item dwMoveSortQuOption"
                  style={{ marginBottom: 5, borderRadius: 2 }}
                  hoverable
                  onClick={() => clickItem(item)}
                >
                  <div className="dw-qu-item">
                    <div className="dw-qu-item-body">
                      <div className={`dw-qu-item-body-order-option ${item.checked ? 'dw-item-checked' : ''}`}>
                        {item.orderIndex > 0 ? (
                          <Tag
                            className="dw-qu-order-num dw-num-order animate__animated animate__tada"
                            style={{ 
                              background: themeColor, 
                              borderColor: themeColor,
                              marginRight: 5
                            }}
                          >
                            {item.orderIndex}
                          </Tag>
                        ) : (
                          <Tag className="dw-qu-order-num dw-num-empty">
                            {item.orderIndex}
                          </Tag>
                        )}
                        <div className="dw-qu-item-option-title">
                          <DwHtmlLabelCommon value={item.optionTitleObj} />
                        </div>
                      </div>
                    </div>
                  </div>
                </Card>
              </CSSTransition>
            );
          })}
        </TransitionGroup>
      </div>
    </Form>
  );
};

export default DwQuOrderOptions;
