// src/components/dw-survey-comp/dw-answer-comp/dw-answer-survey-question/dw-answer-options/dw-qu-option-common2/DwQuOptionCommon2.vue
<template>
  <div>
    <div v-for="(item,optionIndex) in options" :key="`quOption2-${index}-${optionIndex}`">
      <dw-qu-option-common2-item ref="quCommonItem" v-model="survey" :options="options" :qu-index="index" :option-index="optionIndex" :qu-type="quType" @refresh-options="refreshOptions"></dw-qu-option-common2-item>
    </div>
  </div>
</template>

<script>
import DwQuOptionCommon2Item from './DwQuOptionCommon2Item.vue'

export default {
  name: 'DwQuOptionCommon2',
  components: {DwQuOptionCommon2Item},
  model: {
    prop: 'survey',
    event: 'update-survey'
  },
  props: {
    index: {type: Number, default: 0},
    options: {type: Array, default: () => []},
    survey: {type: Object, default: () => {}},
    quType: {type: String, default: ''},
    answer: {type: Object, default: () => {}}
  },
  data () {
    return {
      dragOptions: this.options,
      drag: false
    }
  },
  watch: {
    options: function (newValue, oldValue) {
      // console.log('firstName changed from ' + oldValue + ' to ' + newValue)
      // this.dragOptions = newValue
      // const quCommonItems = this.$refs.quCommonItem
      // for (let i=0; i<quCommonItems.length; i++) quCommonItems[i].dragClick(null)
      this.refreshData()
    }
  },
  methods: {
    onStart () {
      this.drag = true
    },
    onEnd () {
      this.drag = false
      this.refreshOptions(null)
    },
    upAllItemClick () {
      // const curObjs = this.survey.curEditObj
      // for (let i = 0; i < curObjs.length; i++) if (i !== this.itemIndex) this.survey.curEditObj[i].itemClick = false
    },
    refreshOptions (focusIndex) {
      this.$emit('update-options', this.dragOptions)
      // 关于状态的刷新，除通过方法调用硬刷新，还可以通过选项数据上绑定的itemClick实现
      // 先重置所有状态
      this.upAllItemClick()
      this.$nextTick(() => {
        const quCommonItems = this.$refs.quCommonItem
        for (let i=0; i<quCommonItems.length; i++) quCommonItems[i].dragClick(focusIndex)
      })
    },
    refreshData () {
      // 外层option发生变动时同步刷新
      this.dragOptions = this.options
    }
  }
}
</script>

// src/components/dw-survey-comp/dw-answer-comp/dw-answer-survey-question/dw-answer-options/dw-qu-option-common2/DwQuOptionCommon2.tsx
import React, { useEffect, useRef, useState } from 'react';
import DwQuOptionCommon2Item from './DwQuOptionCommon2Item';

interface DwQuOptionCommon2Props {
  index: number;
  options: any[];
  survey: any;
  quType: string;
  answer: any;
  onUpdateOptions?: (options: any[]) => void;
}

const DwQuOptionCommon2: React.FC<DwQuOptionCommon2Props> = ({
  index,
  options,
  survey,
  quType,
  answer,
  onUpdateOptions
}) => {
  const [dragOptions, setDragOptions] = useState(options);
  const [drag, setDrag] = useState(false);
  const quCommonItemRefs = useRef<any[]>([]);

  useEffect(() => {
    refreshData();
  }, [options]);

  const onStart = () => {
    setDrag(true);
  };

  const onEnd = () => {
    setDrag(false);
    refreshOptions(null);
  };

  const upAllItemClick = () => {
    // 重置所有状态
    // 在 React 中，这个功能可能需要通过状态管理来实现
  };

  const refreshOptions = (focusIndex: number | null) => {
    if (onUpdateOptions) {
      onUpdateOptions(dragOptions);
    }
    
    upAllItemClick();
    
    // 使用 setTimeout 模拟 Vue 的 nextTick
    setTimeout(() => {
      quCommonItemRefs.current.forEach((ref, i) => {
        if (ref && ref.dragClick) {
          ref.dragClick(focusIndex);
        }
      });
    }, 0);
  };

  const refreshData = () => {
    setDragOptions(options);
  };

  return (
    <div>
      {options.map((item, optionIndex) => (
        <DwQuOptionCommon2Item
          key={`quOption2-${index}-${optionIndex}`}
          ref={(el: any) => (quCommonItemRefs.current[optionIndex] = el)}
          survey={survey}
          options={options}
          quIndex={index}
          optionIndex={optionIndex}
          quType={quType}
          onRefreshOptions={refreshOptions}
        />
      ))}
    </div>
  );
};

export default DwQuOptionCommon2;
