// src/components/dw-survey-comp/dw-answer-comp/dw-answer-survey-question/dw-answer-questions/dw-answer-qu-upload/DwAnswerQuUpload.vue
<template>
  <div>
    <!--    <div style="background-color: red;margin: 10px;">{{ survey.questions[index].upFileList }}</div>-->
    <!--    <div style="background-color: grey;margin: 10px;">{{ survey.questions[index].anQuestion }}</div>-->
    <el-upload
      :before-remove="beforeRemove"
      :before-upload="beforeAvatarUpload"
      :on-preview="handlePreview"
      :on-remove="handleRemove"
      :on-exceed="handleExceed"
      :on-success="handleSuccess"
      :limit="limit"
      :accept="accept"
      :file-list="upFileList"
      :list-type="listType"
      :action="uploadAction"
      class="upload-demo"
      multiple
    >
      <el-button size="small" type="primary" plain>点击上传</el-button>
      <div slot="tip" class="el-upload__tip">
        <div class="dw-answer-question-remind" style="line-height: 20px;">
          <template v-if="accept!=='' && fileSize>0 && limit >0 ">
            请上传<span class="span-high">{{ accept }}</span>类型文件，单个文件大小不超过<span class="span-high">{{ fileSize }}M</span>，最多只能上传<span class="span-high">{{ limit }}个</span>文件
          </template>
          <template v-if="accept==='' && fileSize>0 && limit >0 ">
            单个文件大小不超过<span class="span-high">{{ fileSize }}M</span>，最多只能上传<span class="span-high">{{ limit }}个</span>文件
          </template>
          <template v-if="accept==='' && fileSize<=0 && limit >0 ">
            最多只能上传<span class="span-high">{{ limit }}个</span>文件
          </template>
        </div>
      </div>
    </el-upload>
    <div v-show="survey.dwDebug">
      <div>{{ upFileList }}</div>
    </div>
  </div>
</template>

<script>

import {answerQuEventCommon} from '../../../dw-utils/dw-survey-answer-common'

export default {
  name: 'DwAnswerQuUpload',
  components: {},
  model: {
    prop: 'survey',
    event: 'update-survey'
  },
  props: {
    index: {type: Number, default: 0},
    survey: {type: Object, default: () => {}},
    answer: {type: Object, default: () => {}}
  },
  data () {
    return {
      upFileList: [],
      // fileList: [],
      limit: 0,
      accept: '',
      listType: 'text', // picture/picture-card
      uploadAction: '/api/dwsurvey/up/up-file-wb.do',
      fileSize: 10
    }
  },
  mounted () {
    const question = this.survey.questions[this.index]
    if (question.hasOwnProperty('fileLimit') && question.fileLimit!==null) this.limit = question.fileLimit
    if (question.hasOwnProperty('fileAccept') && question.fileAccept!==null) {
      const fileAccept = question.fileAccept
      if (fileAccept===0) this.accept = ''
      if (fileAccept===1) this.accept = '.jpg,.jpeg,.png,.gif,.bmp'
      if (fileAccept===2) this.accept = '.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx'
      if (fileAccept===100) this.accept = question.customFileAccept
    }
    if (question.hasOwnProperty('fileSize') && question.fileSize!==null) this.fileSize = question.fileSize
    if (this.survey.questions[this.index].upFileList!==undefined) {
      this.upFileList = this.survey.questions[this.index].upFileList
    }
  },
  methods: {
    handleRemove (file, fileList) {
      console.log(file, fileList)
      this.upFileList = fileList
      this.updateUpFileAnswer()
    },
    handlePreview (file) {
      console.log(file)
    },
    handleExceed (files, fileList) {
      this.$message.warning(`当前限制选择 ${this.limit} 个文件，本次选择了 ${files.length} 个文件，共选择了 ${files.length + fileList.length} 个文件`)
    },
    beforeRemove (file, fileList) {
      // console.debug('beforeRemove file', file)
      // if (!file.raw.hasOwnProperty('checkSize') || file.raw.checkSize===true) return this.$confirm(`确定移除 ${file.name}？`)
    },
    beforeAvatarUpload (file) {
      if (this.fileSize !== null && this.fileSize>0) {
        const isLt2M = file.size / 1024 / 1024 < this.fileSize
        if (!isLt2M) this.$message.warning(`上传文件大小不能超过 ${this.fileSize}MB!`)
        file.checkSize = false
        // console.debug('beforeAvatarUpload file', file)
        return isLt2M
      }
      return true
    },
    handleSuccess (response, file, fileList) {
      console.debug('response', response)
      console.debug('file', file)
      console.debug('fileList', fileList)
      // this.upFileList = fileList
      // this.updateUpFileAnswer()
      const resultCode = response.resultCode
      if (resultCode===200) {
        /*
        const upDatas = response.data
        upDatas.map((item, index) => {
          const anUploadFile = {belongId: null, belongAnswerId: null, quId: null, filePath: item.location, fileName: item.filename, randomCode: ''}
          this.survey.questions[this.index].anUplodFiles.push(anUploadFile)
        })*/
        this.upFileList = fileList
        this.updateUpFileAnswer()
      } else {
        // 提交错误原因
        this.$message.error('上传失败，'+response.resultMsg)
        if (this.upFileList.length>0) {
          // const upFileList = this.upFileList
          // upFileList.splice(-1, 1)
          // this.upFileList = upFileList
          this.upFileList = fileList
          this.upFileList.pop()
        } else {
          this.upFileList = []
        }
        // console.debug('this.upFileList', this.upFileList)
      }
    },
    updateUpFileAnswer () {
      // console.debug(this.upFileList)
      this.survey.questions[this.index].upFileList = this.upFileList
      // getQuestionAnswerData(this.survey.questions[this.index])
      // validateQuestion(this.survey.questions[this.index])
      answerQuEventCommon(this.survey, this.index)
    }
  }
}
</script>

<style scoped>
@import '../../../../../../assets/css/dw-answer.css';
.span-high {
  color: #014ab6;
  font-weight: bold;
}
</style>

// src/components/dw-survey-comp/dw-answer-comp/dw-answer-survey-question/dw-answer-questions/dw-answer-qu-upload/DwAnswerQuUpload.tsx
import React, { useState, useEffect } from 'react';
import { Upload, Button, message, Form } from 'antd';
import { UploadFile } from 'antd/lib/upload/interface';
import { answerQuEventCommon } from '../../../dw-utils/dw-survey-answer-common';
import './DwAnswerQuUpload.css'; // Import the converted CSS

const { Dragger } = Upload;

interface Question {
  fileLimit?: number | null;
  fileAccept?: number | null;
  customFileAccept?: string;
  fileSize?: number | null;
  upFileList?: UploadFile[];
  anUplodFiles?: any[];
  [key: string]: any;
}

interface Survey {
  questions: Question[];
  dwDebug?: boolean;
  [key: string]: any;
}

interface Answer {
  [key: string]: any;
}

interface DwAnswerQuUploadProps {
  index?: number;
  survey: Survey;
  answer?: Answer;
  onUpdateOptions?: (options: any) => void;
}

const DwAnswerQuUpload: React.FC<DwAnswerQuUploadProps> = ({
  index = 0,
  survey,
  answer,
  onUpdateOptions
}) => {
  const [upFileList, setUpFileList] = useState<UploadFile[]>([]);
  const [limit, setLimit] = useState(0);
  const [accept, setAccept] = useState('');
  const [fileSize, setFileSize] = useState(10);
  const uploadAction = '/api/dwsurvey/up/up-file-wb.do';

  useEffect(() => {
    const question = survey.questions[index];
    
    if (question.fileLimit !== undefined && question.fileLimit !== null) {
      setLimit(question.fileLimit);
    }
    
    if (question.fileAccept !== undefined && question.fileAccept !== null) {
      const fileAccept = question.fileAccept;
      if (fileAccept === 0) setAccept('');
      if (fileAccept === 1) setAccept('.jpg,.jpeg,.png,.gif,.bmp');
      if (fileAccept === 2) setAccept('.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx');
      if (fileAccept === 100 && question.customFileAccept) {
        setAccept(question.customFileAccept);
      }
    }
    
    if (question.fileSize !== undefined && question.fileSize !== null) {
      setFileSize(question.fileSize);
    }
    
    if (question.upFileList !== undefined) {
      setUpFileList(question.upFileList);
    }
  }, [index, survey]);

  const handleRemove = (file: UploadFile) => {
    const newFileList = upFileList.filter(f => f.uid !== file.uid);
    setUpFileList(newFileList);
    updateUpFileAnswer(newFileList);
  };

  const handlePreview = (file: UploadFile) => {
    console.log(file);
    // Implement preview logic here
  };

  const handleExceed = () => {
    message.warning(`当前限制选择 ${limit} 个文件`);
  };

  const beforeUpload = (file: File) => {
    if (fileSize > 0) {
      const isLtSize = file.size / 1024 / 1024 < fileSize;
      if (!isLtSize) {
        message.warning(`上传文件大小不能超过 ${fileSize}MB!`);
      }
      return isLtSize;
    }
    return true;
  };

  const handleSuccess = (response: any, file: UploadFile, fileList: UploadFile[]) => {
    if (response.resultCode === 200) {
      setUpFileList(fileList);
      updateUpFileAnswer(fileList);
    } else {
      message.error(`上传失败，${response.resultMsg}`);
      const updatedFileList = [...fileList];
      updatedFileList.pop();
      setUpFileList(updatedFileList);
    }
  };

  const updateUpFileAnswer = (fileList: UploadFile[]) => {
    const updatedSurvey = { ...survey };
    updatedSurvey.questions[index].upFileList = fileList;
    if (onUpdateOptions) {
      onUpdateOptions(updatedSurvey);
    }
    answerQuEventCommon(updatedSurvey, index);
  };

  const getUploadTip = () => {
    if (accept && fileSize > 0 && limit > 0) {
      return (
        <div className="dw-answer-question-remind" style={{ lineHeight: '20px' }}>
          请上传<span className="span-high">{accept}</span>类型文件，单个文件大小不超过
          <span className="span-high">{fileSize}M</span>，最多只能上传
          <span className="span-high">{limit}个</span>文件
        </div>
      );
    } else if (!accept && fileSize > 0 && limit > 0) {
      return (
        <div className="dw-answer-question-remind" style={{ lineHeight: '20px' }}>
          单个文件大小不超过<span className="span-high">{fileSize}M</span>，最多只能上传
          <span className="span-high">{limit}个</span>文件
        </div>
      );
    } else if (!accept && fileSize <= 0 && limit > 0) {
      return (
        <div className="dw-answer-question-remind" style={{ lineHeight: '20px' }}>
          最多只能上传<span className="span-high">{limit}个</span>文件
        </div>
      );
    }
    return null;
  };

  return (
    <Form>
      <div>
        <Upload
          action={uploadAction}
          fileList={upFileList}
          beforeUpload={beforeUpload}
          onRemove={handleRemove}
          onPreview={handlePreview}
          onChange={({ fileList }) => setUpFileList(fileList)}
          onDrop={() => console.log('Dropped files')}
          multiple
          accept={accept}
          maxCount={limit}
        >
          <Button type="primary" ghost>点击上传</Button>
          <div className="ant-upload-hint">
            {getUploadTip()}
          </div>
        </Upload>

        {survey.dwDebug && (
          <div>
            <pre>{JSON.stringify(upFileList, null, 2)}</pre>
          </div>
        )}
      </div>
    </Form>
  );
};

export default DwAnswerQuUpload;
